# Generated by Django 4.0.1 on 2022-03-03 12:41

from django.db import migrations, models
import djongo.models.fields
import testcode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название задачи')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание задачи')),
                ('testinput', models.CharField(max_length=200, verbose_name='Тестовый ввод')),
                ('testoutput', models.CharField(max_length=200, verbose_name='Тестовый вывод')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arr', djongo.models.fields.ArrayField(model_container=testcode.models.TestPk)),
            ],
        ),
    ]
