# Generated by Django 4.0.1 on 2022-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcode', '0002_profile_result_resultolympiad_remove_task_testinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
