# Generated by Django 4.0.1 on 2022-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcode', '0004_testpk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('testinput', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Тестовый ввод')),
                ('testoutput', models.CharField(max_length=200, verbose_name='Тестовый вывод')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
